services:
  db:
    image: postgres:16
    ports:
      - "4321:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: green
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
